### ISSUE TITLE
Telos Cloud Login Integration

### ISSUE THREAD

**Issue by pmjanus** [telosnetwork/telos-bridge#75]
## Overview
Allow users to connect to the bridge using the telos cloud login (gmail).

## Acceptance Criteria
- User can log in through their gmail account and have access to their metakeep account
- User can bridge from their telos cloud login account
## Tasks
- Get Testing App ID
- Setup OAUTH Service
- Get Production App ID

**Comment by rozzaswap** [comment]
Deprioritized indefinitely
